# mac build
language: objective-c
env:
# using compiler: section to do this doesn't seem to work on mac
    - CC=gcc CXX=g++
    - CC=clang CXX=clang++
install:
    - brew install freetype libpng
#    - brew link freetype
#    - sudo easy_install matplotlib
#    - sudo easy_install pip
    - pip install "git+http://github.com/matplotlib/matplotlib.git#egg=matplotlib"
    - gem install gist
script:
    - COIN_PROJECT=CoinBazaar/projects/GIMPy/trunk
    - echo "CC is $CC, CXX is $CXX, COIN_PROJECT is $COIN_PROJECT"
    - svn co -q --non-interactive --trust-server-cert https://projects.coin-or.org/svn/$COIN_PROJECT ~/$COIN_PROJECT
# do svn update in case of connectivity trouble during checkout
    - cd ~/$COIN_PROJECT && svn update --non-interactive --trust-server-cert
    - for i in `ls ThirdParty/*/get.*`; do cd `dirname $i` && ./`basename $i` && cd ../..; done
# add a newline at end of CoinUtils/src/CoinLpIO.hpp until fixed
#    - echo "" >> CoinUtils/src/CoinLpIO.hpp
    - mkdir build && cd build && ../configure -C
    - curl -Sso wrap.rb https://gist.github.com/roidrage/5238585/raw
    - chmod +x wrap.rb && ./wrap.rb "make all -j4 > make.log 2>&1"
    - echo "CONFIGURE AND MAKE LOGS UPLOADED TO URL" && gist config.log make.log
# should upload more of the subdirectory config.log's too once that works
    - make install && make test
