# linux build
language: cpp
compiler:
    - gcc
    - clang
before_install:
    - sudo apt-get update -qq
install:
    - sudo apt-get install gfortran
    - gem install gist
script:
    - COIN_PROJECT=CoinUtils/trunk
    - echo "CC is $CC, CXX is $CXX, COIN_PROJECT is $COIN_PROJECT"
    - svn co -q --non-interactive --trust-server-cert https://projects.coin-or.org/svn/$COIN_PROJECT ~/$COIN_PROJECT
# do svn update in case of connectivity trouble during checkout
    - cd ~/$COIN_PROJECT && svn update --non-interactive --trust-server-cert
    - for i in `ls ThirdParty/*/get.*`; do cd `dirname $i` && ./`basename $i` && cd ../..; done
# install matplotlib and start xvfb to emulate a display if GIMPy included
    - "if test -e $COIN_PROJECT/GIMPy; then sudo apt-get install python-matplotlib && export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start; fi"
# add a newline at end of CoinUtils/src/CoinLpIO.hpp until fixed
#    - mkdir -p CoinUtils/src && echo "" >> CoinUtils/src/CoinLpIO.hpp
    - mkdir build && cd build && ../configure -C
# download and use a ruby wrapper that just outputs a 10-second heartbeat dot
    - curl -Sso wrap.rb https://gist.github.com/roidrage/5238585/raw
    - chmod +x wrap.rb && ./wrap.rb "make all -j4 > make.log 2>&1"
    - echo "CONFIGURE AND MAKE LOGS UPLOADED TO URL" && gist config.log make.log
# should upload more of the subdirectory config.log's too once that works
    - make install && make test
