# mac build
language: objective-c
compiler:
    - gcc
    - clang
install:
    - gem install gist
script:
    - svn co -q --non-interactive --trust-server-cert https://projects.coin-or.org/svn/CoinBinary/CoinAll/trunk ~/CoinAll-trunk
# do svn update in case of connectivity trouble during checkout
    - cd ~/CoinAll-trunk && svn update
    - for i in ASL Blas Lapack Glpk Metis Mumps; do cd ThirdParty/$i && ./get.$i && cd ../..; done
# add a newline at end of CoinUtils/src/CoinLpIO.hpp until fixed
    - echo "" >> CoinUtils/src/CoinLpIO.hpp
    - echo "CC is $CC, CXX is $CXX"
    - mkdir build && cd build && ../configure -C
    - curl -Sso wrap.rb https://gist.github.com/roidrage/5238585/raw
    - chmod +x wrap.rb && ./wrap.rb "make all -j2 2>&1 > make.log"
    - echo "CONFIGURE AND MAKE LOGS UPLOADED TO URL" && gist make.log config.log */config.log */*/config.log
    - make install && make test
