language: objective-c
before_install:
    - brew update > /dev/null
install:
    - brew install gfortran
    - svn export -q --non-interactive --trust-server-cert https://projects.coin-or.org/svn/CoinBinary/CoinAll/stable/1.7 ~/CoinAll-1.7
script:
    - cd ~/CoinAll-1.7 && ./get.AllThirdParty
    - mkdir build && cd build && ../configure -C
    - (AM_LDFLAGS="--quiet" make all -j4 -s)
    - make install
    - make test
