language: objective-c
compiler:
    - gcc
install:
    - gem install gist
    - curl -s -O www.coin-or.org/download/source/OS/OS-2.8.1.tgz
    - tar -xzf OS-2.8.1.tgz
script:
    - cd OS-2.8.1 && for i in ASL Blas Lapack Glpk Metis Mumps; do cd ThirdParty/$i && ./get.$i && cd ../..; done
    - mkdir build && cd build && ../configure -C
    - (make all -j4 | gist)
    - echo "make output was uploaded to above URL" && make install && make test
