language: cpp
compiler:
    - gcc
before_install:
    - sudo apt-get update -qq
install:
    - sudo apt-get install gfortran
    - gem install gist
    - svn export -q --non-interactive --trust-server-cert https://projects.coin-or.org/svn/CoinBinary/CoinAll/releases/1.7.2 ~/CoinAll-1.7.2
script:
    - cd ~/CoinAll-1.7.2 && ./get.AllThirdParty
    - mkdir build && cd build && ../configure -C
    - (make all -j4 | gist)
    - echo "make output was uploaded to above URL"
    - make install
    - make test
